// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/victorsantoso/endeus/domain"
	entity "github.com/victorsantoso/endeus/entity"

	mock "github.com/stretchr/testify/mock"
)

// RecipeUsecase is an autogenerated mock type for the RecipeUsecase type
type RecipeUsecase struct {
	mock.Mock
}

// CreateRecipe provides a mock function with given fields: ctx, createRecipeDTO
func (_m *RecipeUsecase) CreateRecipe(ctx context.Context, createRecipeDTO *domain.CreateRecipeDTO) error {
	ret := _m.Called(ctx, createRecipeDTO)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecipe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateRecipeDTO) error); ok {
		r0 = rf(ctx, createRecipeDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRecipeCategory provides a mock function with given fields: ctx, createRecipeCategoryDTO
func (_m *RecipeUsecase) CreateRecipeCategory(ctx context.Context, createRecipeCategoryDTO *domain.CreateRecipeCategoryDTO) error {
	ret := _m.Called(ctx, createRecipeCategoryDTO)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecipeCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateRecipeCategoryDTO) error); ok {
		r0 = rf(ctx, createRecipeCategoryDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRecipeById provides a mock function with given fields: ctx, recipeId
func (_m *RecipeUsecase) DeleteRecipeById(ctx context.Context, recipeId int64) error {
	ret := _m.Called(ctx, recipeId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecipeById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, recipeId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRecipeById provides a mock function with given fields: ctx, recipeId
func (_m *RecipeUsecase) GetRecipeById(ctx context.Context, recipeId int64) (*entity.Recipe, error) {
	ret := _m.Called(ctx, recipeId)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipeById")
	}

	var r0 *entity.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.Recipe, error)); ok {
		return rf(ctx, recipeId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Recipe); ok {
		r0 = rf(ctx, recipeId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, recipeId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecipeCategories provides a mock function with given fields: ctx
func (_m *RecipeUsecase) GetRecipeCategories(ctx context.Context) ([]entity.RecipeCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipeCategories")
	}

	var r0 []entity.RecipeCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.RecipeCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.RecipeCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RecipeCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecipeCategoryById provides a mock function with given fields: ctx, categoryId
func (_m *RecipeUsecase) GetRecipeCategoryById(ctx context.Context, categoryId int64) (*entity.RecipeCategory, error) {
	ret := _m.Called(ctx, categoryId)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipeCategoryById")
	}

	var r0 *entity.RecipeCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.RecipeCategory, error)); ok {
		return rf(ctx, categoryId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.RecipeCategory); ok {
		r0 = rf(ctx, categoryId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RecipeCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, categoryId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecipes provides a mock function with given fields: ctx, getRecipesQueryFilter
func (_m *RecipeUsecase) GetRecipes(ctx context.Context, getRecipesQueryFilter *domain.GetRecipesQueryFilter) ([]entity.Recipe, error) {
	ret := _m.Called(ctx, getRecipesQueryFilter)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipes")
	}

	var r0 []entity.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GetRecipesQueryFilter) ([]entity.Recipe, error)); ok {
		return rf(ctx, getRecipesQueryFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GetRecipesQueryFilter) []entity.Recipe); ok {
		r0 = rf(ctx, getRecipesQueryFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.GetRecipesQueryFilter) error); ok {
		r1 = rf(ctx, getRecipesQueryFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRecipe provides a mock function with given fields: ctx, recipeId, updateRecipeDTO
func (_m *RecipeUsecase) UpdateRecipe(ctx context.Context, recipeId int64, updateRecipeDTO *domain.UpdateRecipeDTO) error {
	ret := _m.Called(ctx, recipeId, updateRecipeDTO)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecipe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *domain.UpdateRecipeDTO) error); ok {
		r0 = rf(ctx, recipeId, updateRecipeDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRecipeUsecase creates a new instance of RecipeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecipeUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecipeUsecase {
	mock := &RecipeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
