// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/victorsantoso/endeus/domain"
)

// UserUsecase is an autogenerated mock type for the UserUsecase type
type UserUsecase struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, loginDTO
func (_m *UserUsecase) Login(ctx context.Context, loginDTO *domain.LoginDTO) (string, error) {
	ret := _m.Called(ctx, loginDTO)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.LoginDTO) (string, error)); ok {
		return rf(ctx, loginDTO)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.LoginDTO) string); ok {
		r0 = rf(ctx, loginDTO)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.LoginDTO) error); ok {
		r1 = rf(ctx, loginDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, registerDTO
func (_m *UserUsecase) Register(ctx context.Context, registerDTO *domain.RegisterDTO) (string, error) {
	ret := _m.Called(ctx, registerDTO)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RegisterDTO) (string, error)); ok {
		return rf(ctx, registerDTO)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RegisterDTO) string); ok {
		r0 = rf(ctx, registerDTO)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.RegisterDTO) error); ok {
		r1 = rf(ctx, registerDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserUsecase creates a new instance of UserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUsecase {
	mock := &UserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
